import connectDB from '../lib/mongodb.js';
import Restaurant from '../models/Restaurant.js';

const sampleRestaurants = [
  // BANGALORE RESTAURANTS
  {
    name: 'Chat Street - Authentic Street Food Hub',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
    rating: 4.3,
    reviewCount: 892,
    cuisine: ['Street Food', 'Chats', 'Indian'],
    dietary: 'veg',
    deliveryTime: '20-35 min',
    deliveryFee: '₹25',
    minimumOrder: '₹150',
    distance: '1.5 km',
    popularDishes: ['Pani Puri', 'Bhel Puri', 'Dahi Puri', 'Samosa Chaat'],
    offers: ['10% off on orders above ₹300', 'Free delivery'],
    isOpen: true,
    isFavorite: false,
    priceRange: 'budget',
    features: ['Street food', 'Quick service', 'Traditional recipes'],
    status: 'OPEN',
    subStatus: 'BUSY',
    location: {
      address: 'Koramangala 8th Block',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560034'
    },
    dishes: [
      {
        name: 'Pani Puri',
        description: 'Crispy puris filled with tangy tamarind water and spicy potato mixture',
        price: '₹60',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '5 min',
        calories: '120 cal',
        rating: 4.5,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Bhel Puri',
        description: 'Puffed rice mixed with chutneys, vegetables, and crunchy sev',
        price: '₹80',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '8 min',
        calories: '180 cal',
        rating: 4.3,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Dahi Puri',
        description: 'Puris filled with yogurt, chutneys, and sweet tamarind sauce',
        price: '₹90',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '10 min',
        calories: '220 cal',
        rating: 4.4,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Samosa Chaat',
        description: 'Crushed samosa topped with yogurt, chutneys, and spices',
        price: '₹100',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '12 min',
        calories: '280 cal',
        rating: 4.6,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Pav Bhaji',
        description: 'Spiced vegetable curry served with soft bread rolls',
        price: '₹120',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '15 min',
        calories: '320 cal',
        rating: 4.2,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      }
    ]
  },
  {
    name: 'Spice Garden - Traditional Indian Dining',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
    rating: 4.5,
    reviewCount: 1247,
    cuisine: ['Indian', 'North Indian', 'Mughlai'],
    dietary: 'both',
    deliveryTime: '30-45 min',
    deliveryFee: '₹30',
    minimumOrder: '₹200',
    distance: '2.1 km',
    popularDishes: ['Butter Chicken', 'Paneer Tikka', 'Dal Makhani', 'Biryani'],
    offers: ['20% off on orders above ₹500', 'Free delivery'],
    isOpen: true,
    isFavorite: false,
    priceRange: 'mid-range',
    features: ['Pure veg available', 'Family restaurant', 'Fine dining'],
    status: 'OPEN',
    subStatus: 'NORMAL',
    location: {
      address: 'Indiranagar 100 Feet Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560038'
    },
    dishes: [
      {
        name: 'Butter Chicken',
        description: 'Tender chicken cooked in rich, creamy tomato-based gravy with butter and cream',
        price: '₹450',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'medium',
        prepTime: '25 min',
        calories: '450 cal',
        rating: 4.8,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Paneer Tikka',
        description: 'Marinated cottage cheese grilled to perfection with Indian spices',
        price: '₹380',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '20 min',
        calories: '280 cal',
        rating: 4.5,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Dal Makhani',
        description: 'Creamy black lentils slow-cooked with butter and cream',
        price: '₹280',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '30 min',
        calories: '320 cal',
        rating: 4.3,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: false,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Biryani',
        description: 'Fragrant basmati rice cooked with aromatic spices and tender meat',
        price: '₹520',
        image: 'https://images.unsplash.com/photo-1563379091339-03246963d4a9?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'hot',
        prepTime: '30 min',
        calories: '550 cal',
        rating: 4.7,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Naan',
        description: 'Soft and fluffy Indian bread baked in tandoor',
        price: '₹60',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop',
        category: 'breads',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '10 min',
        calories: '120 cal',
        rating: 4.2,
        isPopular: false,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      }
    ]
  },
  {
    name: 'Pizza Palace - Artisanal Italian',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
    rating: 4.4,
    reviewCount: 756,
    cuisine: ['Italian', 'Pizza', 'Pasta'],
    dietary: 'both',
    deliveryTime: '25-40 min',
    deliveryFee: '₹40',
    minimumOrder: '₹300',
    distance: '1.8 km',
    popularDishes: ['Margherita Pizza', 'Pepperoni Pizza', 'BBQ Chicken Pizza', 'Garlic Bread'],
    offers: ['Buy 1 Get 1 Free on Pizzas'],
    isOpen: true,
    isFavorite: true,
    priceRange: 'mid-range',
    features: ['Wood-fired oven', 'Fresh ingredients'],
    status: 'OPEN',
    subStatus: 'BUSY',
    location: {
      address: 'Whitefield Main Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560066'
    },
    dishes: [
      {
        name: 'Margherita Pizza',
        description: 'Classic tomato sauce with mozzarella cheese and fresh basil',
        price: '₹350',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '20 min',
        calories: '280 cal',
        rating: 4.5,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Pepperoni Pizza',
        description: 'Spicy pepperoni with mozzarella cheese and tomato sauce',
        price: '₹420',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'medium',
        prepTime: '22 min',
        calories: '320 cal',
        rating: 4.6,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'BBQ Chicken Pizza',
        description: 'BBQ sauce with grilled chicken and red onions',
        price: '₹450',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'medium',
        prepTime: '25 min',
        calories: '380 cal',
        rating: 4.4,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Garlic Bread',
        description: 'Toasted bread with garlic butter and herbs',
        price: '₹120',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '8 min',
        calories: '180 cal',
        rating: 4.2,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Pasta Carbonara',
        description: 'Creamy pasta with bacon, eggs, and parmesan cheese',
        price: '₹320',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'mild',
        prepTime: '18 min',
        calories: '420 cal',
        rating: 4.4,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      }
    ]
  },
  {
    name: 'Golden Dragon - Authentic Chinese',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
    rating: 4.2,
    reviewCount: 634,
    cuisine: ['Chinese', 'Asian'],
    dietary: 'both',
    deliveryTime: '35-50 min',
    deliveryFee: '₹35',
    minimumOrder: '₹250',
    distance: '3.2 km',
    popularDishes: ['Kung Pao Chicken', 'Sweet and Sour Fish', 'Dim Sum', 'Spring Rolls'],
    offers: ['Free delivery on orders above ₹400'],
    isOpen: true,
    isFavorite: false,
    priceRange: 'mid-range',
    features: ['Authentic Chinese', 'Spicy options'],
    status: 'OPEN',
    subStatus: 'VERY_BUSY',
    location: {
      address: 'MG Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560001'
    },
    dishes: [
      {
        name: 'Kung Pao Chicken',
        description: 'Spicy diced chicken with peanuts and vegetables in chili sauce',
        price: '₹420',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'hot',
        prepTime: '30 min',
        calories: '380 cal',
        rating: 4.4,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Sweet and Sour Fish',
        description: 'Crispy fish in tangy sweet and sour sauce',
        price: '₹380',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'mild',
        prepTime: '25 min',
        calories: '320 cal',
        rating: 4.2,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Dim Sum',
        description: 'Steamed dumplings filled with vegetables and meat',
        price: '₹280',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'non-veg',
        spiceLevel: 'mild',
        prepTime: '20 min',
        calories: '240 cal',
        rating: 4.5,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Spring Rolls',
        description: 'Crispy vegetable rolls with sweet chili sauce',
        price: '₹200',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '15 min',
        calories: '180 cal',
        rating: 4.1,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Fried Rice',
        description: 'Stir-fried rice with mixed vegetables and soy sauce',
        price: '₹180',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '15 min',
        calories: '280 cal',
        rating: 4.1,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      }
    ]
  },
  {
    name: 'Fusion Bites - Multi-Cuisine Delight',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
    rating: 4.1,
    reviewCount: 445,
    cuisine: ['Multi-cuisine', 'Fusion', 'International'],
    dietary: 'both',
    deliveryTime: '40-55 min',
    deliveryFee: '₹45',
    minimumOrder: '₹350',
    distance: '4.1 km',
    popularDishes: ['Indo-Chinese Noodles', 'Mexican Tacos', 'Thai Green Curry', 'American Burger'],
    offers: ['15% off for first order'],
    isOpen: true,
    isFavorite: false,
    priceRange: 'mid-range',
    features: ['Multi-cuisine', 'Fusion dishes'],
    status: 'OPEN',
    subStatus: 'NORMAL',
    location: {
      address: 'Electronic City Phase 1',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560100'
    },
    dishes: [
      {
        name: 'Indo-Chinese Noodles',
        description: 'Indian-style Chinese noodles with vegetables and spices',
        price: '₹240',
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '20 min',
        calories: '320 cal',
        rating: 4.3,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: true,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'Mexican Tacos',
        description: 'Soft tacos with grilled vegetables and salsa',
        price: '₹280',
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'medium',
        prepTime: '18 min',
        calories: '280 cal',
        rating: 4.2,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Thai Green Curry',
        description: 'Spicy coconut curry with vegetables and herbs',
        price: '₹360',
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'veg',
        spiceLevel: 'hot',
        prepTime: '25 min',
        calories: '320 cal',
        rating: 4.4,
        isPopular: true,
        isChefSpecial: true,
        isQuickOrder: false,
        isTrending: true,
        isAvailable: true
      },
      {
        name: 'American Burger',
        description: 'Classic beef burger with lettuce, tomato, and cheese',
        price: '₹320',
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
        category: 'mains',
        dietary: 'non-veg',
        spiceLevel: 'mild',
        prepTime: '15 min',
        calories: '450 cal',
        rating: 4.3,
        isPopular: true,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      },
      {
        name: 'Mediterranean Salad',
        description: 'Fresh salad with olives, feta cheese, and olive oil',
        price: '₹220',
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
        category: 'starters',
        dietary: 'veg',
        spiceLevel: 'mild',
        prepTime: '12 min',
        calories: '180 cal',
        rating: 4.1,
        isPopular: false,
        isChefSpecial: false,
        isQuickOrder: true,
        isTrending: false,
        isAvailable: true
      }
    ]
  }
];

async function seedDatabase() {
  try {
    console.log('Connecting to database...');
    await connectDB();
    
    console.log('Clearing existing data...');
    await Restaurant.deleteMany({});
    
    console.log('Creating restaurants with embedded dishes...');
    const createdRestaurants = await Restaurant.insertMany(sampleRestaurants);
    
    console.log('Database seeded successfully!');
    console.log(`Created ${createdRestaurants.length} restaurants`);
    
    // Count total dishes
    const totalDishes = createdRestaurants.reduce((sum, restaurant) => sum + restaurant.dishes.length, 0);
    console.log(`Created ${totalDishes} dishes across all restaurants`);
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();